"""Create articles and openai_usage tables

Revision ID: 001
Revises: 
Create Date: 2024-01-01 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('structure', sa.Text(), nullable=False),
    sa.Column('article', sa.Text(), nullable=False),
    sa.Column('seo_score', sa.Float(), nullable=False),
    sa.Column('model_used', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('openai_usage',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('article_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('openai_usage')
    op.drop_table('articles')
    # ### end Alembic commands ### 